name: Terraform Create Database Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'iac/db/**'
  pull_request:
    branches:
      - master
    paths:
      - 'iac/db/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./iac/db

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_environment: ${{ vars.ENVIRONMENT }}
      TF_VAR_pg_password: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Print environment variables
        run: |
          echo "project_id: $TF_VAR_project_id"
          echo "environment: $TF_VAR_environment"
          echo "pg_password: $TF_VAR_pg_password"
          echo "region: $TF_VAR_region"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure GCP credentials
        uses: google-github-actions/setup-gcloud@v2.1.0

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Show GCP credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          gcloud auth list

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
